// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"server/ent/priority"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Priority is the model entity for the Priority schema.
type Priority struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PriorityQuery when eager-loading is set.
	Edges        PriorityEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PriorityEdges holds the relations/edges for other nodes in the graph.
type PriorityEdges struct {
	// Todos holds the value of the todos edge.
	Todos []*Todo `json:"todos,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TodosOrErr returns the Todos value or an error if the edge
// was not loaded in eager-loading.
func (e PriorityEdges) TodosOrErr() ([]*Todo, error) {
	if e.loadedTypes[0] {
		return e.Todos, nil
	}
	return nil, &NotLoadedError{edge: "todos"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Priority) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case priority.FieldID, priority.FieldName:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Priority fields.
func (pr *Priority) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case priority.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				pr.ID = value.String
			}
		case priority.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				pr.Name = value.String
			}
		default:
			pr.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Priority.
// This includes values selected through modifiers, order, etc.
func (pr *Priority) Value(name string) (ent.Value, error) {
	return pr.selectValues.Get(name)
}

// QueryTodos queries the "todos" edge of the Priority entity.
func (pr *Priority) QueryTodos() *TodoQuery {
	return NewPriorityClient(pr.config).QueryTodos(pr)
}

// Update returns a builder for updating this Priority.
// Note that you need to call Priority.Unwrap() before calling this method if this Priority
// was returned from a transaction, and the transaction was committed or rolled back.
func (pr *Priority) Update() *PriorityUpdateOne {
	return NewPriorityClient(pr.config).UpdateOne(pr)
}

// Unwrap unwraps the Priority entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pr *Priority) Unwrap() *Priority {
	_tx, ok := pr.config.driver.(*txDriver)
	if !ok {
		panic("ent: Priority is not a transactional entity")
	}
	pr.config.driver = _tx.drv
	return pr
}

// String implements the fmt.Stringer.
func (pr *Priority) String() string {
	var builder strings.Builder
	builder.WriteString("Priority(")
	builder.WriteString(fmt.Sprintf("id=%v, ", pr.ID))
	builder.WriteString("name=")
	builder.WriteString(pr.Name)
	builder.WriteByte(')')
	return builder.String()
}

// Priorities is a parsable slice of Priority.
type Priorities []*Priority
