// Code generated by ent, DO NOT EDIT.

package ent

import (
	"server/ent/label"
	"server/ent/priority"
	"server/ent/schema"
	"server/ent/status"
	"server/ent/todo"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	labelFields := schema.Label{}.Fields()
	_ = labelFields
	// labelDescValue is the schema descriptor for value field.
	labelDescValue := labelFields[1].Descriptor()
	// label.ValueValidator is a validator for the "value" field. It is called by the builders before save.
	label.ValueValidator = labelDescValue.Validators[0].(func(string) error)
	// labelDescCreatedAt is the schema descriptor for created_at field.
	labelDescCreatedAt := labelFields[2].Descriptor()
	// label.DefaultCreatedAt holds the default value on creation for the created_at field.
	label.DefaultCreatedAt = labelDescCreatedAt.Default.(func() time.Time)
	// labelDescUpdatedAt is the schema descriptor for updated_at field.
	labelDescUpdatedAt := labelFields[3].Descriptor()
	// label.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	label.DefaultUpdatedAt = labelDescUpdatedAt.Default.(func() time.Time)
	// label.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	label.UpdateDefaultUpdatedAt = labelDescUpdatedAt.UpdateDefault.(func() time.Time)
	priorityFields := schema.Priority{}.Fields()
	_ = priorityFields
	// priorityDescName is the schema descriptor for name field.
	priorityDescName := priorityFields[1].Descriptor()
	// priority.NameValidator is a validator for the "name" field. It is called by the builders before save.
	priority.NameValidator = priorityDescName.Validators[0].(func(string) error)
	// priorityDescCreatedAt is the schema descriptor for created_at field.
	priorityDescCreatedAt := priorityFields[2].Descriptor()
	// priority.DefaultCreatedAt holds the default value on creation for the created_at field.
	priority.DefaultCreatedAt = priorityDescCreatedAt.Default.(func() time.Time)
	// priorityDescUpdatedAt is the schema descriptor for updated_at field.
	priorityDescUpdatedAt := priorityFields[3].Descriptor()
	// priority.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	priority.DefaultUpdatedAt = priorityDescUpdatedAt.Default.(func() time.Time)
	// priority.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	priority.UpdateDefaultUpdatedAt = priorityDescUpdatedAt.UpdateDefault.(func() time.Time)
	statusFields := schema.Status{}.Fields()
	_ = statusFields
	// statusDescValue is the schema descriptor for value field.
	statusDescValue := statusFields[1].Descriptor()
	// status.ValueValidator is a validator for the "value" field. It is called by the builders before save.
	status.ValueValidator = statusDescValue.Validators[0].(func(string) error)
	// statusDescCreatedAt is the schema descriptor for created_at field.
	statusDescCreatedAt := statusFields[2].Descriptor()
	// status.DefaultCreatedAt holds the default value on creation for the created_at field.
	status.DefaultCreatedAt = statusDescCreatedAt.Default.(func() time.Time)
	// statusDescUpdatedAt is the schema descriptor for updated_at field.
	statusDescUpdatedAt := statusFields[3].Descriptor()
	// status.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	status.DefaultUpdatedAt = statusDescUpdatedAt.Default.(func() time.Time)
	// status.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	status.UpdateDefaultUpdatedAt = statusDescUpdatedAt.UpdateDefault.(func() time.Time)
	todoFields := schema.Todo{}.Fields()
	_ = todoFields
	// todoDescTitle is the schema descriptor for title field.
	todoDescTitle := todoFields[1].Descriptor()
	// todo.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	todo.TitleValidator = todoDescTitle.Validators[0].(func(string) error)
	// todoDescStatusID is the schema descriptor for status_id field.
	todoDescStatusID := todoFields[5].Descriptor()
	// todo.DefaultStatusID holds the default value on creation for the status_id field.
	todo.DefaultStatusID = todoDescStatusID.Default.(int)
	// todoDescCreatedAt is the schema descriptor for created_at field.
	todoDescCreatedAt := todoFields[6].Descriptor()
	// todo.DefaultCreatedAt holds the default value on creation for the created_at field.
	todo.DefaultCreatedAt = todoDescCreatedAt.Default.(func() time.Time)
	// todoDescUpdatedAt is the schema descriptor for updated_at field.
	todoDescUpdatedAt := todoFields[7].Descriptor()
	// todo.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	todo.DefaultUpdatedAt = todoDescUpdatedAt.Default.(func() time.Time)
	// todo.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	todo.UpdateDefaultUpdatedAt = todoDescUpdatedAt.UpdateDefault.(func() time.Time)
}
