services:
  server:
    build:
      context: .
      dockerfile: ./server/docker/Dockerfile
    command: reflex -r '(\.go$|go\.mod)' -s go run main.go
    volumes:
      - ./server:/go/src/server
    environment:
      TZ: Asia/Tokyo
      PORT: ${PORT:-8001}
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: db
      DB_PORT: 5432
    ports:
      - "${PORT:-8001}:8001"
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
      TZ: Asia/Tokyo
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} || exit 1" ]
      interval: 1s
      timeout: 5s
      retries: 5

volumes:
  db-data:



