openapi: 3.1.0
info:
  title: Todo App API
  description: An API for managing todo items.
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
    description: Local server

paths:
  /todos:
    get:
      summary: Get all todo items
      responses:
        "200":
          description: A list of todo items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Todo"
    post:
      summary: Create a new todo item
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TodoInput"
      responses:
        "201":
          description: Todo item created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Todo"

  /todos/{id}:
    get:
      summary: Get a todo item by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The ID of the todo item to retrieve
      responses:
        "200":
          description: A single todo item
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Todo"
        "404":
          description: Todo item not found

    put:
      summary: Update a todo item by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The ID of the todo item to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TodoInput"
      responses:
        "200":
          description: Todo item updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Todo"
        "404":
          description: Todo item not found

    delete:
      summary: Delete a todo item by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The ID of the todo item to delete
      responses:
        "204":
          description: Todo item deleted
        "404":
          description: Todo item not found

components:
  schemas:
    Todo:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        isCompleted:
          type: boolean
      required:
        - id
        - title

    TodoInput:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        isCompleted:
          type: boolean
      required:
        - title
