openapi: 3.1.0
info:
  title: Todo App API
  description: An API for managing todo items.
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
    description: Local server

paths:
  /todos:
    get:
      summary: Get all todo items
      responses:
        "200":
          description: A list of todo items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Todo"
        # default: # default エラーレスポンスを追加
        #   description: Unexpected error
        #   content:
        #     application/json:
        #       schema:
        #         $ref: "#/components/schemas/ErrorResponse"

    # post:
    #   summary: Create a new todo item
    #   requestBody:
    #     required: true
    #     content:
    #       application/json:
    #         schema:
    #           $ref: "#/components/schemas/TodoInput"
    #   responses:
    #     "201":
    #       description: Todo item created
    #       content:
    #         application/json:
    #           schema:
    #             $ref: "#/components/schemas/Todo"
    #     default: # default エラーレスポンスを追加
    #       description: Unexpected error
    #       content:
    #         application/json:
    #           schema:
    #             $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    Priority:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
      required:
        - id
        - name
    Todo:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        priority:
          $ref: "#/components/schemas/Priority"
      required:
        - id
        - title
        - priority

    TodoInput:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        isCompleted:
          type: boolean
      required:
        - title

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        code:
          type: integer
      required:
        - error
        - code
