openapi: 3.1.0
info:
  title: Todo App API
  description: An API for managing todo items.
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
    description: Local server

paths:
  /todos:
    get:
      summary: Get all todo items
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
          required: false
          description: The number of items to return
        - in: query
          name: offset
          schema:
            type: integer
            minimum: 0
          required: false
          description: The number of items to skip before starting to collect the result set
        - in: query
          name: labelIDs
          schema:
            type: array
            items:
              type: integer
          required: false
        - in: query
          name: priorityID
          schema:
            type: integer
          required: false
          description: Criteria to filter todo items
        - in: query
          name: statusID
          schema:
            type: integer
          required: false
          description: Criteria to filter todo items
        - in: query
          name: title
          schema:
            type: string
          required: false
          description: Criteria to filter todo items
        - in: query
          name: description
          schema:
            type: string
          required: false
          description: Criteria to filter todo items
      responses:
        "200":
          description: A list of todo items
          content:
            application/json:
              schema:
                type: object
                properties:
                  todoList:
                    type: array
                    items:
                      $ref: "#/components/schemas/Todo"
                  pageCount:
                    type: integer
                    description: Total number of pages
                required:
                  - todoList
                  - pageCount
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /search:
    get:
      summary: Search for todo items
      responses:
        "200":
          description: A list of todo items
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseSearchTodo"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /todo:
    post:
      summary: Create a new todo item
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateTodoInput"
      responses:
        "201":
          description: Todo item created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateTodoResponse"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    Priority:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
      required:
        - id
        - name
    Status:
      type: object
      properties:
        id:
          type: integer
        value:
          type: string
      required:
        - id
        - value
    Label:
      type: object
      properties:
        id:
          type: integer
        value:
          type: string
      required:
        - id
        - value

    Todo:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        createdAt:
          type: string
          format: date-time
        labels:
          type: array
          items:
            $ref: "#/components/schemas/Label"
        finishedAt:
          type: string
          format: date-time
        priority:
          $ref: "#/components/schemas/Priority"
        status:
          $ref: "#/components/schemas/Status"
      required:
        - id
        - title
        - priority
        - status
        - labels
        - createdAt

    ResponseSearchTodo:
      type: object
      properties:
        labels:
          type: array
          items:
            $ref: "#/components/schemas/Label"
        priorities:
          type: array
          items:
            $ref: "#/components/schemas/Priority"
        status:
          type: array
          items:
            $ref: "#/components/schemas/Status"
      required:
        - labels
        - priorities
        - status

    CreateTodoResponse:
      type: object
      properties:
        id:
          type: integer
      required:
        - id

    WhereTodoInput:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        priorityID:
          type: integer
        statusID:
          type: integer

    CreateTodoInput:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        labelIDs:
          type: array
          items:
            type: integer
        priorityID:
          type: integer
        statusID:
          type: integer
      required:
        - title
        - description
        - labelIDs
        - priorityID
        - statusID

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
      required:
        - error
