-- Create "priorities" table
CREATE TABLE "priorities" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying NOT NULL, PRIMARY KEY ("id"));
-- Create "todos" table
CREATE TABLE "todos" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "title" character varying NOT NULL, "description" character varying NULL, "name" character varying NOT NULL, PRIMARY KEY ("id"));
-- Create "priority_todos" table
CREATE TABLE "priority_todos" ("priority_id" bigint NOT NULL, "todo_id" bigint NOT NULL, PRIMARY KEY ("priority_id", "todo_id"), CONSTRAINT "priority_todos_priority_id" FOREIGN KEY ("priority_id") REFERENCES "priorities" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "priority_todos_todo_id" FOREIGN KEY ("todo_id") REFERENCES "todos" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
