-- Modify "todos" table
ALTER TABLE "todos" ADD COLUMN "finished_at" timestamptz NULL;
-- Create "status" table
CREATE TABLE "status" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "value" character varying NOT NULL, PRIMARY KEY ("id"));
