-- Create "priorities" table
CREATE TABLE "priorities" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying NOT NULL, PRIMARY KEY ("id"));
-- Create "todos" table
CREATE TABLE "todos" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "title" character varying NOT NULL, "description" character varying NULL, "name" character varying NOT NULL, "priority_id" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "todos_priorities_todo" FOREIGN KEY ("priority_id") REFERENCES "priorities" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "todos_priority_id_key" to table: "todos"
CREATE UNIQUE INDEX "todos_priority_id_key" ON "todos" ("priority_id");
