-- Create "labels" table
CREATE TABLE "labels" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "value" character varying NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- Create "label_todos" table
CREATE TABLE "label_todos" ("label_id" bigint NOT NULL, "todo_id" bigint NOT NULL, PRIMARY KEY ("label_id", "todo_id"), CONSTRAINT "label_todos_label_id" FOREIGN KEY ("label_id") REFERENCES "labels" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "label_todos_todo_id" FOREIGN KEY ("todo_id") REFERENCES "todos" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
