// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// TodoPost implements POST /todo operation.
	//
	// Create a new todo item.
	//
	// POST /todo
	TodoPost(ctx context.Context, req *CreateTodoInput) (*Todo, error)
	// TodosGet implements GET /todos operation.
	//
	// Get all todo items.
	//
	// GET /todos
	TodosGet(ctx context.Context, req *TodoInput) ([]Todo, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
