// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// TodosGet implements GET /todos operation.
	//
	// Get all todo items.
	//
	// GET /todos
	TodosGet(ctx context.Context) ([]Todo, error)
	// TodosIDDelete implements DELETE /todos/{id} operation.
	//
	// Delete a todo item by ID.
	//
	// DELETE /todos/{id}
	TodosIDDelete(ctx context.Context, params TodosIDDeleteParams) (TodosIDDeleteRes, error)
	// TodosIDGet implements GET /todos/{id} operation.
	//
	// Get a todo item by ID.
	//
	// GET /todos/{id}
	TodosIDGet(ctx context.Context, params TodosIDGetParams) (TodosIDGetRes, error)
	// TodosIDPut implements PUT /todos/{id} operation.
	//
	// Update a todo item by ID.
	//
	// PUT /todos/{id}
	TodosIDPut(ctx context.Context, req *TodoInput, params TodosIDPutParams) (TodosIDPutRes, error)
	// TodosPost implements POST /todos operation.
	//
	// Create a new todo item.
	//
	// POST /todos
	TodosPost(ctx context.Context, req *TodoInput) (*Todo, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
