// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// TodosGet implements GET /todos operation.
//
// Get all todo items.
//
// GET /todos
func (UnimplementedHandler) TodosGet(ctx context.Context) (r []Todo, _ error) {
	return r, ht.ErrNotImplemented
}

// TodosPost implements POST /todos operation.
//
// Create a new todo item.
//
// POST /todos
func (UnimplementedHandler) TodosPost(ctx context.Context, req *TodoInput) (r *Todo, _ error) {
	return r, ht.ErrNotImplemented
}
