// Code generated by ogen, DO NOT EDIT.
package ogen

type TodosIDDeleteRes interface {
	todosIDDeleteRes()
}

type TodosIDGetRes interface {
	todosIDGetRes()
}

type TodosIDPutRes interface {
	todosIDPutRes()
}
