// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"time"
)

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/Priority
type Priority struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

// GetID returns the value of ID.
func (s *Priority) GetID() int {
	return s.ID
}

// GetName returns the value of Name.
func (s *Priority) GetName() string {
	return s.Name
}

// SetID sets the value of ID.
func (s *Priority) SetID(val int) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Priority) SetName(val string) {
	s.Name = val
}

// Ref: #/components/schemas/Status
type Status struct {
	ID    int    `json:"id"`
	Value string `json:"value"`
}

// GetID returns the value of ID.
func (s *Status) GetID() int {
	return s.ID
}

// GetValue returns the value of Value.
func (s *Status) GetValue() string {
	return s.Value
}

// SetID sets the value of ID.
func (s *Status) SetID(val int) {
	s.ID = val
}

// SetValue sets the value of Value.
func (s *Status) SetValue(val string) {
	s.Value = val
}

// Ref: #/components/schemas/Todo
type Todo struct {
	ID          int         `json:"id"`
	Title       string      `json:"title"`
	Description OptString   `json:"description"`
	CreatedAt   time.Time   `json:"createdAt"`
	FinishedAt  OptDateTime `json:"finishedAt"`
	Priority    Priority    `json:"priority"`
	Status      Status      `json:"status"`
}

// GetID returns the value of ID.
func (s *Todo) GetID() int {
	return s.ID
}

// GetTitle returns the value of Title.
func (s *Todo) GetTitle() string {
	return s.Title
}

// GetDescription returns the value of Description.
func (s *Todo) GetDescription() OptString {
	return s.Description
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Todo) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetFinishedAt returns the value of FinishedAt.
func (s *Todo) GetFinishedAt() OptDateTime {
	return s.FinishedAt
}

// GetPriority returns the value of Priority.
func (s *Todo) GetPriority() Priority {
	return s.Priority
}

// GetStatus returns the value of Status.
func (s *Todo) GetStatus() Status {
	return s.Status
}

// SetID sets the value of ID.
func (s *Todo) SetID(val int) {
	s.ID = val
}

// SetTitle sets the value of Title.
func (s *Todo) SetTitle(val string) {
	s.Title = val
}

// SetDescription sets the value of Description.
func (s *Todo) SetDescription(val OptString) {
	s.Description = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Todo) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetFinishedAt sets the value of FinishedAt.
func (s *Todo) SetFinishedAt(val OptDateTime) {
	s.FinishedAt = val
}

// SetPriority sets the value of Priority.
func (s *Todo) SetPriority(val Priority) {
	s.Priority = val
}

// SetStatus sets the value of Status.
func (s *Todo) SetStatus(val Status) {
	s.Status = val
}

// Ref: #/components/schemas/TodoInput
type TodoInput struct {
	Limit  int `json:"limit"`
	Offset int `json:"offset"`
}

// GetLimit returns the value of Limit.
func (s *TodoInput) GetLimit() int {
	return s.Limit
}

// GetOffset returns the value of Offset.
func (s *TodoInput) GetOffset() int {
	return s.Offset
}

// SetLimit sets the value of Limit.
func (s *TodoInput) SetLimit(val int) {
	s.Limit = val
}

// SetOffset sets the value of Offset.
func (s *TodoInput) SetOffset(val int) {
	s.Offset = val
}
